version: '3.9'
services:
  lp-aceleracao:
    image: caddy:alpine
    networks:
      - arkanlabsint
    command: 
      - /bin/sh
      - -c
      - |
        # Baixando o vídeo pesado (171MB) na VPS para não sobrecarregar o git/api
        mkdir -p /srv/hero
        wget -qO /srv/hero/solarzap-hero-video-wvga.mp4 https://lp-solarzap-aceleracao.surge.sh/hero/solarzap-hero-video-wvga.mp4
        
        # Servindo os arquivos e garantindo o SSL (Traefik labels)
        caddy file-server --root /srv --listen :80 --access-log
    volumes:
      - ./dist:/srv
      - ./nginx.conf:/etc/caddy/Caddyfile:ro
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.lp-aceleracao.rule=Host(`lp.aceleracao.solarzap.com.br`)"
        - "traefik.http.routers.lp-aceleracao.entrypoints=websecure"
        - "traefik.http.routers.lp-aceleracao.tls=true"
        - "traefik.http.routers.lp-aceleracao.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.lp-aceleracao.service=lp-aceleracao-svc"
        - "traefik.http.services.lp-aceleracao-svc.loadbalancer.server.port=80"
        - "traefik.docker.network=arkanlabsint"

networks:
  arkanlabsint:
    external: true
